/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

/**
 *
 * @author Emmanuel
 */
public class AnularCompra extends javax.swing.JInternalFrame{

    /**
     * Creates new form AnularCompra
     */
    public AnularCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAnulCompra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAnulCompra = new javax.swing.JTable();
        pnlOpcAnulCompra = new javax.swing.JPanel();
        calenDeAnulCompra = new com.toedter.calendar.JDateChooser();
        calenAAnulCompra = new com.toedter.calendar.JDateChooser();
        btnBuscAnulCompra = new javax.swing.JButton();
        btnAnulAnulCompra = new javax.swing.JButton();
        lblDeAnulCompra = new javax.swing.JLabel();
        lblAAnulCompra = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Anulación de compras");

        pnlAnulCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas Anuladas"));

        jtblAnulCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NO DE VENTA", "VENDEDOR", "NOMBRE", "PRECIO", "CANTIDAD", "TOTAL", "FECHA DE VENTA"
            }
        ));
        jScrollPane1.setViewportView(jtblAnulCompra);

        pnlOpcAnulCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de búsqueda"));

        btnBuscAnulCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        btnBuscAnulCompra.setText("Buscar");

        btnAnulAnulCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anular.png"))); // NOI18N
        btnAnulAnulCompra.setText("Anular");

        lblDeAnulCompra.setText("Desde:");

        lblAAnulCompra.setText("Hasta:");

        javax.swing.GroupLayout pnlOpcAnulCompraLayout = new javax.swing.GroupLayout(pnlOpcAnulCompra);
        pnlOpcAnulCompra.setLayout(pnlOpcAnulCompraLayout);
        pnlOpcAnulCompraLayout.setHorizontalGroup(
            pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcAnulCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenDeAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeAnulCompra))
                .addGap(42, 42, 42)
                .addGroup(pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenAAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAAnulCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnBuscAnulCompra)
                .addGap(68, 68, 68)
                .addComponent(btnAnulAnulCompra)
                .addGap(42, 42, 42))
        );
        pnlOpcAnulCompraLayout.setVerticalGroup(
            pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcAnulCompraLayout.createSequentialGroup()
                .addGroup(pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOpcAnulCompraLayout.createSequentialGroup()
                        .addGroup(pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpcAnulCompraLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblDeAnulCompra))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcAnulCompraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAAnulCompra)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calenDeAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calenAAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlOpcAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscAnulCompra)
                        .addComponent(btnAnulAnulCompra)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAnulCompraLayout = new javax.swing.GroupLayout(pnlAnulCompra);
        pnlAnulCompra.setLayout(pnlAnulCompraLayout);
        pnlAnulCompraLayout.setHorizontalGroup(
            pnlAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnulCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addGroup(pnlAnulCompraLayout.createSequentialGroup()
                        .addComponent(pnlOpcAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAnulCompraLayout.setVerticalGroup(
            pnlAnulCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnulCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAnulCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAnulCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnularCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnularCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnularCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnularCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnularCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnulAnulCompra;
    private javax.swing.JButton btnBuscAnulCompra;
    private com.toedter.calendar.JDateChooser calenAAnulCompra;
    private com.toedter.calendar.JDateChooser calenDeAnulCompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblAnulCompra;
    private javax.swing.JLabel lblAAnulCompra;
    private javax.swing.JLabel lblDeAnulCompra;
    private javax.swing.JPanel pnlAnulCompra;
    private javax.swing.JPanel pnlOpcAnulCompra;
    // End of variables declaration//GEN-END:variables
}
