/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoferreteria.BO.BuscarComprasBO;
import proyectoferreteria.BO.BuscarVentasBO;
import proyectoferreteria.DAO.BuscarComprasDAO;
import proyectoferreteria.DAO.BuscarVentasDAO;

/**
 *
 * @author joni_
 */
public class BuscarCompras extends javax.swing.JInternalFrame {

    DefaultTableModel dtm= new DefaultTableModel(
        new Object [][] { },
        new String [] {
        "ID venta","Total","Descuento","Fecha","Estatus","ID empleado","ID cliente"
    });
    BuscarComprasBO ObjBuscarComprasBO= new BuscarComprasBO();
    BuscarComprasDAO ObjBuscarComprasDAO= new BuscarComprasDAO();
    public BuscarCompras() {
        initComponents();
        ActualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdtFechaInicio = new com.toedter.calendar.JDateChooser();
        jdtFechaFinal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jblBuscarVentas = new javax.swing.JTable();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFinal = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Buscar Compras");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Venta"));

        jLabel1.setText("Buscar por fecha:");

        jLabel2.setText("Inicio:");

        jLabel3.setText("Final:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdtFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jdtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jdtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jblBuscarVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jblBuscarVentas);

        lblFechaInicio.setText("jLabel4");

        lblFechaFinal.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblFechaFinal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaInicio)
                        .addGap(26, 26, 26)
                        .addComponent(lblFechaFinal)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ActualizarTabla1();
    }//GEN-LAST:event_jButton1ActionPerformed

    public BuscarComprasBO RecoletarDatos(){
        
        try{
             String dia = Integer.toString(jdtFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
             String mes = Integer.toString(jdtFechaInicio.getCalendar().get(Calendar.MONTH)+1);
             String ano = Integer.toString(jdtFechaInicio.getCalendar().get(Calendar.YEAR));
             String FechaInicio = (ano+"/"+mes+"/"+dia); 
        
             String dia2 = Integer.toString(jdtFechaFinal.getCalendar().get(Calendar.DAY_OF_MONTH));
             String mes2 = Integer.toString(jdtFechaFinal.getCalendar().get(Calendar.MONTH)+1);
             String ano2 = Integer.toString(jdtFechaFinal.getCalendar().get(Calendar.YEAR));
             String FechaFinal = (ano2+"/"+mes2+"/"+dia2);
             
             lblFechaInicio.setText(FechaInicio);
             lblFechaFinal.setText(FechaFinal);

             ObjBuscarComprasBO.setFechaInicio(FechaInicio);
             ObjBuscarComprasBO.setFechaFinal(FechaFinal);

        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " +e);
        }
       return ObjBuscarComprasBO;
    }
    
    public void ActualizarTabla1(){
    jblBuscarVentas.setModel(ObjBuscarComprasDAO.BuscarFecha(RecoletarDatos()));
    } 
     public void ActualizarTabla(){
    jblBuscarVentas.setModel(ObjBuscarComprasDAO.Buscar());
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jblBuscarVentas;
    private com.toedter.calendar.JDateChooser jdtFechaFinal;
    private com.toedter.calendar.JDateChooser jdtFechaInicio;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicio;
    // End of variables declaration//GEN-END:variables
}
