/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import proyectoferreteria.BO.UsuariosBO;
import proyectoferreteria.DAO.UsuariosDAO;

/**
 *
 * @author ORTIZ
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    UsuariosDAO metodp = new UsuariosDAO();
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public class PresionarEnter extends KeyAdapter { 
      public void keyPressed(KeyEvent ke) {
          if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
              btnEntrLogiActionPerformed(null);
          }
      }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuLogi = new javax.swing.JTextField();
        txtContraLogi = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrLogi = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuLogi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuLogi.setBorder(null);
        txtUsuLogi.setOpaque(false);
        jPanel1.add(txtUsuLogi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 290, 50));

        txtContraLogi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContraLogi.setBorder(null);
        jPanel1.add(txtContraLogi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 280, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_txt.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pass_txt.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnEntrLogi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio_norm.png"))); // NOI18N
        btnEntrLogi.setBorder(null);
        btnEntrLogi.setBorderPainted(false);
        btnEntrLogi.setContentAreaFilled(false);
        btnEntrLogi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrLogi.setFocusPainted(false);
        btnEntrLogi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio_rol.png"))); // NOI18N
        btnEntrLogi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrLogiActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrLogi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/canc_norm.png"))); // NOI18N
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/canc_rol.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frame.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrLogiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrLogiActionPerformed
        // TODO add your handling code here:
        UsuariosBO objUsuari = new UsuariosBO();
        objUsuari.setUsuario(txtUsuLogi.getText());
        objUsuari.setContrasena(txtContraLogi.getText());
        String Usuario = "";
        String Coontraseña = "";

        ResultSet resultado = metodp.Buscar(objUsuari);
        try 
        {           
            while(resultado.next())
            {
                Usuario = resultado.getString(8);
                Coontraseña = resultado.getString(9);
            }
            if(objUsuari.getUsuario().equals(Usuario)&& objUsuari.getContrasena().equals(Coontraseña))
            {
                PaginaPrincipal v = new PaginaPrincipal();
                v.setVisible(true);
                this.hide();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
            }
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
        }         
        
    }//GEN-LAST:event_btnEntrLogiActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEntrLogi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraLogi;
    private javax.swing.JTextField txtUsuLogi;
    // End of variables declaration//GEN-END:variables
}
