/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

/**
 *
 * @author Emmanuel
 */
public class NuevoEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoEmpleados
     */
    public NuevoEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpnlNuevoEmpleado = new javax.swing.JTabbedPane();
        pnlBusNuevEmple = new javax.swing.JPanel();
        pnlOpcNuevEmple = new javax.swing.JPanel();
        calenDeBusNuevEmple = new com.toedter.calendar.JDateChooser();
        calenABusNuevEmple = new com.toedter.calendar.JDateChooser();
        btnBuscBusNuevEmple = new javax.swing.JButton();
        btnElimBusNuevEmple = new javax.swing.JButton();
        lblDeBusNuevEmple = new javax.swing.JLabel();
        lblABusNuevEmple = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBusNuevEmple = new javax.swing.JTable();
        pnlNuevEmple = new javax.swing.JPanel();
        lblIdNuevEmple = new javax.swing.JLabel();
        lblNomNuevEmple = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlEstadoNuevEmple = new javax.swing.JPanel();
        rbtnActiNueEmple = new javax.swing.JRadioButton();
        rbtnInacNueEmple = new javax.swing.JRadioButton();
        lblFechNuevEmple = new javax.swing.JLabel();
        lblemailNuevEmple = new javax.swing.JLabel();
        lblSuelNuevEmple = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIDNuevEmple = new javax.swing.JTextField();
        txtNombNuevEmple = new javax.swing.JTextField();
        txtApelliNuevEmple = new javax.swing.JTextField();
        rbtnMascNueEmple = new javax.swing.JRadioButton();
        rbtnFemeNueEmple = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEmailNueEmple = new javax.swing.JTextField();
        txtSuelNueEmple = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtApelliNueEmple1 = new javax.swing.JTextField();
        txtApelliNueEmple2 = new javax.swing.JTextField();
        txtApelliNueEmple3 = new javax.swing.JTextField();
        txtUsuarioUser = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        pnlBusNuevEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Empleado"));

        pnlOpcNuevEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de búsqueda"));

        btnBuscBusNuevEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        btnBuscBusNuevEmple.setText("Buscar");

        btnElimBusNuevEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anular.png"))); // NOI18N
        btnElimBusNuevEmple.setText("Eliminar");

        lblDeBusNuevEmple.setText("Desde:");

        lblABusNuevEmple.setText("Hasta:");

        javax.swing.GroupLayout pnlOpcNuevEmpleLayout = new javax.swing.GroupLayout(pnlOpcNuevEmple);
        pnlOpcNuevEmple.setLayout(pnlOpcNuevEmpleLayout);
        pnlOpcNuevEmpleLayout.setHorizontalGroup(
            pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcNuevEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenDeBusNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeBusNuevEmple))
                .addGap(42, 42, 42)
                .addGroup(pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenABusNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblABusNuevEmple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnBuscBusNuevEmple)
                .addGap(73, 73, 73)
                .addComponent(btnElimBusNuevEmple)
                .addGap(37, 37, 37))
        );
        pnlOpcNuevEmpleLayout.setVerticalGroup(
            pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcNuevEmpleLayout.createSequentialGroup()
                .addGroup(pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOpcNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpcNuevEmpleLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblDeBusNuevEmple))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcNuevEmpleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblABusNuevEmple)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calenDeBusNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calenABusNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlOpcNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscBusNuevEmple)
                        .addComponent(btnElimBusNuevEmple)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbBusNuevEmple.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tbBusNuevEmple);

        javax.swing.GroupLayout pnlBusNuevEmpleLayout = new javax.swing.GroupLayout(pnlBusNuevEmple);
        pnlBusNuevEmple.setLayout(pnlBusNuevEmpleLayout);
        pnlBusNuevEmpleLayout.setHorizontalGroup(
            pnlBusNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusNuevEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBusNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlOpcNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBusNuevEmpleLayout.setVerticalGroup(
            pnlBusNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusNuevEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnlNuevoEmpleado.addTab("Buscar", pnlBusNuevEmple);

        pnlNuevEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        lblIdNuevEmple.setText("ID Empleado:");

        lblNomNuevEmple.setText("Nombre:");

        jLabel3.setText("Apelldios:");

        jLabel4.setText("Sexo:");

        pnlEstadoNuevEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        rbtnActiNueEmple.setText("ACTIVO");

        rbtnInacNueEmple.setText("INACTIVO");

        javax.swing.GroupLayout pnlEstadoNuevEmpleLayout = new javax.swing.GroupLayout(pnlEstadoNuevEmple);
        pnlEstadoNuevEmple.setLayout(pnlEstadoNuevEmpleLayout);
        pnlEstadoNuevEmpleLayout.setHorizontalGroup(
            pnlEstadoNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoNuevEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnActiNueEmple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnInacNueEmple)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEstadoNuevEmpleLayout.setVerticalGroup(
            pnlEstadoNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadoNuevEmpleLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(pnlEstadoNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnActiNueEmple)
                    .addComponent(rbtnInacNueEmple)))
        );

        lblFechNuevEmple.setText("Fecha de ingreso:");

        lblemailNuevEmple.setText("Email:");

        lblSuelNuevEmple.setText("Sueldo:");

        jLabel9.setText("Fecha de nacimiento:");

        jLabel10.setText("Dirección:");

        jLabel11.setText("Teléfono");

        jLabel12.setText("Celular:");

        rbtnMascNueEmple.setText("Masculino");

        rbtnFemeNueEmple.setText("Femenino");
        rbtnFemeNueEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemeNueEmpleActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel13.setText("INE:");

        jLabel14.setText("Usuario:");

        jLabel15.setText("Contraseña:");

        jLabel16.setText("Tipo de usuario:");

        jPasswordField1.setText("jPasswordField1");

        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero", "Vendedor" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/palomita.png"))); // NOI18N
        jButton1.setText("Agregar");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        jButton2.setText("Modificar");

        javax.swing.GroupLayout pnlNuevEmpleLayout = new javax.swing.GroupLayout(pnlNuevEmple);
        pnlNuevEmple.setLayout(pnlNuevEmpleLayout);
        pnlNuevEmpleLayout.setHorizontalGroup(
            pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdNuevEmple)
                                    .addComponent(lblNomNuevEmple)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombNuevEmple)
                                    .addComponent(txtApelliNuevEmple, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(rbtnMascNueEmple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnFemeNueEmple)
                                .addGap(18, 18, 18)))
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addComponent(lblFechNuevEmple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblemailNuevEmple)
                                    .addComponent(lblSuelNuevEmple))
                                .addGap(61, 61, 61)
                                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailNueEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSuelNueEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlEstadoNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                        .addComponent(txtApelliNueEmple2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtApelliNueEmple1)
                                    .addComponent(txtApelliNueEmple3))
                                .addGap(67, 67, 67)
                                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(21, 21, 21)
                                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsuarioUser)
                                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                                .addGap(140, 140, 140))
                            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButton1)
                                .addGap(54, 54, 54)
                                .addComponent(jButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        pnlNuevEmpleLayout.setVerticalGroup(
            pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdNuevEmple)
                            .addComponent(txtIDNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomNuevEmple)
                            .addComponent(txtNombNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApelliNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechNuevEmple)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblemailNuevEmple)
                            .addComponent(txtEmailNueEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSuelNuevEmple)
                            .addComponent(txtSuelNueEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbtnMascNueEmple)
                            .addComponent(rbtnFemeNueEmple))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnlEstadoNuevEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtApelliNueEmple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtApelliNueEmple3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtApelliNueEmple2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuevEmpleLayout.createSequentialGroup()
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtUsuarioUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(pnlNuevEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );

        tbpnlNuevoEmpleado.addTab("Nuevo/Modificar", pnlNuevEmple);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpnlNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpnlNuevoEmpleado)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnFemeNueEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemeNueEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemeNueEmpleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscBusNuevEmple;
    private javax.swing.JButton btnElimBusNuevEmple;
    private com.toedter.calendar.JDateChooser calenABusNuevEmple;
    private com.toedter.calendar.JDateChooser calenDeBusNuevEmple;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblABusNuevEmple;
    private javax.swing.JLabel lblDeBusNuevEmple;
    private javax.swing.JLabel lblFechNuevEmple;
    private javax.swing.JLabel lblIdNuevEmple;
    private javax.swing.JLabel lblNomNuevEmple;
    private javax.swing.JLabel lblSuelNuevEmple;
    private javax.swing.JLabel lblemailNuevEmple;
    private javax.swing.JPanel pnlBusNuevEmple;
    private javax.swing.JPanel pnlEstadoNuevEmple;
    private javax.swing.JPanel pnlNuevEmple;
    private javax.swing.JPanel pnlOpcNuevEmple;
    private javax.swing.JRadioButton rbtnActiNueEmple;
    private javax.swing.JRadioButton rbtnFemeNueEmple;
    private javax.swing.JRadioButton rbtnInacNueEmple;
    private javax.swing.JRadioButton rbtnMascNueEmple;
    private javax.swing.JTable tbBusNuevEmple;
    private javax.swing.JTabbedPane tbpnlNuevoEmpleado;
    private javax.swing.JTextField txtApelliNueEmple1;
    private javax.swing.JTextField txtApelliNueEmple2;
    private javax.swing.JTextField txtApelliNueEmple3;
    private javax.swing.JTextField txtApelliNuevEmple;
    private javax.swing.JTextField txtEmailNueEmple;
    private javax.swing.JTextField txtIDNuevEmple;
    private javax.swing.JTextField txtNombNuevEmple;
    private javax.swing.JTextField txtSuelNueEmple;
    private javax.swing.JTextField txtUsuarioUser;
    // End of variables declaration//GEN-END:variables
}
