/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class RespaldarBD extends javax.swing.JInternalFrame {

    /**
     * Creates new form RespaldarBD
     */
    public RespaldarBD() {
        initComponents();
        txtBDRespBD.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRespBD = new javax.swing.JPanel();
        lblBDRespBD = new javax.swing.JLabel();
        txtBDRespBD = new javax.swing.JTextField();
        lblRespalRespBD = new javax.swing.JLabel();
        txtRespalRespBD = new javax.swing.JTextField();
        btnGeneRespBD = new javax.swing.JButton();

        setClosable(true);
        setTitle("Backup");

        pnlRespBD.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Respaldo"));

        lblBDRespBD.setText("Base de datos:");

        txtBDRespBD.setText("Ferreteria");

        lblRespalRespBD.setText("Respaldar en:");

        txtRespalRespBD.setEditable(false);
        txtRespalRespBD.setText("Escritorio");

        btnGeneRespBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bdrpBD.png"))); // NOI18N
        btnGeneRespBD.setText("Generar");
        btnGeneRespBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneRespBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRespBDLayout = new javax.swing.GroupLayout(pnlRespBD);
        pnlRespBD.setLayout(pnlRespBDLayout);
        pnlRespBDLayout.setHorizontalGroup(
            pnlRespBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRespBDLayout.createSequentialGroup()
                .addGroup(pnlRespBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRespBDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBDRespBD)
                        .addGap(15, 15, 15)
                        .addComponent(txtBDRespBD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRespBDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRespalRespBD)
                        .addGap(18, 18, 18)
                        .addComponent(txtRespalRespBD, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRespBDLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnGeneRespBD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        pnlRespBDLayout.setVerticalGroup(
            pnlRespBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRespBDLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRespBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRespBDLayout.createSequentialGroup()
                        .addGroup(pnlRespBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBDRespBD)
                            .addComponent(txtBDRespBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(pnlRespBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRespalRespBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRespalRespBD)))
                .addGap(33, 33, 33)
                .addComponent(btnGeneRespBD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRespBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRespBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneRespBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneRespBDActionPerformed
        // TODO add your handling code here:
        try{
           Path o= Paths.get("C:\\Users\\joni_\\OneDrive\\Documentos\\Ferreteria.s3db");
           Path d=Paths.get("C:\\Users\\joni_\\Desktop\\Ferreteria.s3db");
           Files.copy(o,d,StandardCopyOption.REPLACE_EXISTING);
           JOptionPane.showMessageDialog(null,"El backup fue realizado exitosamente");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error: " + e);
       } 
    }//GEN-LAST:event_btnGeneRespBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespaldarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespaldarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespaldarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespaldarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespaldarBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneRespBD;
    private javax.swing.JLabel lblBDRespBD;
    private javax.swing.JLabel lblRespalRespBD;
    private javax.swing.JPanel pnlRespBD;
    private javax.swing.JTextField txtBDRespBD;
    private javax.swing.JTextField txtRespalRespBD;
    // End of variables declaration//GEN-END:variables
}
