/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class RestaurarBD extends javax.swing.JInternalFrame {

    /**
     * Creates new form RestaurarBD
     */
    public RestaurarBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRestBD = new javax.swing.JPanel();
        lblRespalRestBD = new javax.swing.JLabel();
        txtRespalRestBD = new javax.swing.JTextField();
        btnGeneRestBD = new javax.swing.JButton();
        lblRespalRestBD1 = new javax.swing.JLabel();
        txtRespalRestBD1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Restauración de la base de datos");

        pnlRestBD.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Restauración"));

        lblRespalRestBD.setText("Restaurar en:");

        txtRespalRestBD.setEditable(false);
        txtRespalRestBD.setText("ProyectoProgramacion");

        btnGeneRestBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bdrtBD.png"))); // NOI18N
        btnGeneRestBD.setText("Restaurar");
        btnGeneRestBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneRestBDActionPerformed(evt);
            }
        });

        lblRespalRestBD1.setText("Base de datos");

        txtRespalRestBD1.setEditable(false);
        txtRespalRestBD1.setText("Ferreteria");

        javax.swing.GroupLayout pnlRestBDLayout = new javax.swing.GroupLayout(pnlRestBD);
        pnlRestBD.setLayout(pnlRestBDLayout);
        pnlRestBDLayout.setHorizontalGroup(
            pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestBDLayout.createSequentialGroup()
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRestBDLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnGeneRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRestBDLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRestBDLayout.createSequentialGroup()
                                .addComponent(lblRespalRestBD1)
                                .addGap(18, 18, 18)
                                .addComponent(txtRespalRestBD1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRestBDLayout.createSequentialGroup()
                                .addComponent(lblRespalRestBD)
                                .addGap(18, 18, 18)
                                .addComponent(txtRespalRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        pnlRestBDLayout.setVerticalGroup(
            pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestBDLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespalRestBD1)
                    .addComponent(txtRespalRestBD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespalRestBD)
                    .addComponent(txtRespalRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGeneRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneRestBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneRestBDActionPerformed
        // TODO add your handling code here:
        try{
           Path o= Paths.get("RespaldoBD\\Ferreteria.s3db");
           Path d=Paths.get("Ferreteria.s3db");
           Files.copy(o,d,StandardCopyOption.REPLACE_EXISTING);
           JOptionPane.showMessageDialog(null,"La restauracion fue realizada exitosamente");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error: " + e);
       } 
    }//GEN-LAST:event_btnGeneRestBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneRestBD;
    private javax.swing.JLabel lblRespalRestBD;
    private javax.swing.JLabel lblRespalRestBD1;
    private javax.swing.JPanel pnlRestBD;
    private javax.swing.JTextField txtRespalRestBD;
    private javax.swing.JTextField txtRespalRestBD1;
    // End of variables declaration//GEN-END:variables
}
