/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

/**
 *
 * @author Emmanuel
 */
public class RestaurarBD extends javax.swing.JInternalFrame {

    /**
     * Creates new form RestaurarBD
     */
    public RestaurarBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRestBD = new javax.swing.JPanel();
        lblUserRestBD = new javax.swing.JLabel();
        txtUserRestBD = new javax.swing.JTextField();
        lblContrRestBD = new javax.swing.JLabel();
        lblRespalRestBD = new javax.swing.JLabel();
        txtRespalRestBD = new javax.swing.JTextField();
        btnSeleccRestBD = new javax.swing.JButton();
        btnGeneRestBD = new javax.swing.JButton();
        btnCancRestBD = new javax.swing.JButton();
        txtContrRestBD = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Restauración de la base de datos");

        pnlRestBD.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Restauración"));

        lblUserRestBD.setText("Usuario:");

        txtUserRestBD.setText("root");

        lblContrRestBD.setText("Contraseña:");

        lblRespalRestBD.setText("Respaldar de:");

        txtRespalRestBD.setEditable(false);

        btnSeleccRestBD.setText("Seleccionar");

        btnGeneRestBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bdrtBD.png"))); // NOI18N
        btnGeneRestBD.setText("Generar");

        btnCancRestBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancRestBD.setText("Cancelar");

        txtContrRestBD.setText("jPasswordField1");

        javax.swing.GroupLayout pnlRestBDLayout = new javax.swing.GroupLayout(pnlRestBD);
        pnlRestBD.setLayout(pnlRestBDLayout);
        pnlRestBDLayout.setHorizontalGroup(
            pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestBDLayout.createSequentialGroup()
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRestBDLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRestBDLayout.createSequentialGroup()
                                .addComponent(lblRespalRestBD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRespalRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccRestBD))
                            .addGroup(pnlRestBDLayout.createSequentialGroup()
                                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserRestBD)
                                    .addComponent(lblContrRestBD))
                                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlRestBDLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txtUserRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlRestBDLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContrRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnlRestBDLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnGeneRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnCancRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        pnlRestBDLayout.setVerticalGroup(
            pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestBDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserRestBD)
                    .addComponent(txtUserRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrRestBD)
                    .addComponent(txtContrRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespalRestBD)
                    .addComponent(txtRespalRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccRestBD))
                .addGap(18, 18, 18)
                .addGroup(pnlRestBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeneRestBD)
                    .addComponent(btnCancRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRestBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancRestBD;
    private javax.swing.JButton btnGeneRestBD;
    private javax.swing.JButton btnSeleccRestBD;
    private javax.swing.JLabel lblContrRestBD;
    private javax.swing.JLabel lblRespalRestBD;
    private javax.swing.JLabel lblUserRestBD;
    private javax.swing.JPanel pnlRestBD;
    private javax.swing.JPasswordField txtContrRestBD;
    private javax.swing.JTextField txtRespalRestBD;
    private javax.swing.JTextField txtUserRestBD;
    // End of variables declaration//GEN-END:variables
}
