/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

/**
 *
 * @author Emmanuel
 */
public class VentasFallidas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentasFallidas
     */
    public VentasFallidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVentaFall = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVentFall = new javax.swing.JTable();
        pnlOpcVenReal = new javax.swing.JPanel();
        calenDeVenFall = new com.toedter.calendar.JDateChooser();
        calenAVenFall = new com.toedter.calendar.JDateChooser();
        btnBuscVenFall = new javax.swing.JButton();
        btnImpriVenFall = new javax.swing.JButton();
        lblDeVenFall = new javax.swing.JLabel();
        lblAVenFall = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ventas Fallidas");

        pnlVentaFall.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas Fallidas"));

        jtblVentFall.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NO DE VEBNTA", "VENDEDOR", "NOMBRE", "PRECIO", "CANTIDAD", "TOTAL", "FECHA DE VENTA"
            }
        ));
        jScrollPane1.setViewportView(jtblVentFall);

        pnlOpcVenReal.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de búsqueda"));

        btnBuscVenFall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        btnBuscVenFall.setText("Buscar");

        btnImpriVenFall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        btnImpriVenFall.setText("Imprimir");

        lblDeVenFall.setText("Desde:");

        lblAVenFall.setText("Hasta:");

        javax.swing.GroupLayout pnlOpcVenRealLayout = new javax.swing.GroupLayout(pnlOpcVenReal);
        pnlOpcVenReal.setLayout(pnlOpcVenRealLayout);
        pnlOpcVenRealLayout.setHorizontalGroup(
            pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenDeVenFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeVenFall))
                .addGap(42, 42, 42)
                .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenAVenFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAVenFall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnBuscVenFall)
                .addGap(68, 68, 68)
                .addComponent(btnImpriVenFall)
                .addGap(42, 42, 42))
        );
        pnlOpcVenRealLayout.setVerticalGroup(
            pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                        .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblDeVenFall))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcVenRealLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAVenFall)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calenDeVenFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calenAVenFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscVenFall)
                        .addComponent(btnImpriVenFall)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVentaFallLayout = new javax.swing.GroupLayout(pnlVentaFall);
        pnlVentaFall.setLayout(pnlVentaFallLayout);
        pnlVentaFallLayout.setHorizontalGroup(
            pnlVentaFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentaFallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlVentaFallLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(pnlOpcVenReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVentaFallLayout.setVerticalGroup(
            pnlVentaFallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentaFallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcVenReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVentaFall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlVentaFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasFallidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasFallidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasFallidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasFallidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasFallidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscVenFall;
    private javax.swing.JButton btnImpriVenFall;
    private com.toedter.calendar.JDateChooser calenAVenFall;
    private com.toedter.calendar.JDateChooser calenDeVenFall;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblVentFall;
    private javax.swing.JLabel lblAVenFall;
    private javax.swing.JLabel lblDeVenFall;
    private javax.swing.JPanel pnlOpcVenReal;
    private javax.swing.JPanel pnlVentaFall;
    // End of variables declaration//GEN-END:variables
}
