/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria.GUI;

/**
 *
 * @author Emmanuel
 */
public class VentasRealizadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentasRealizadas
     */
    public VentasRealizadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVentaReal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVentReal = new javax.swing.JTable();
        pnlOpcVenReal = new javax.swing.JPanel();
        calenDeVenReal = new com.toedter.calendar.JDateChooser();
        calenAVenFall = new com.toedter.calendar.JDateChooser();
        btnBuscVenReal = new javax.swing.JButton();
        btnImpriVenReal = new javax.swing.JButton();
        lblDeVenReal = new javax.swing.JLabel();
        lblAVenReal = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ventas realizadas");

        pnlVentaReal.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas Realizadas"));

        jtblVentReal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NO DE VENTA", "VENDEDOR", "NOMBRE", "PRECIO", "CANTIDAD", "TOTAL", "FECHA DE VENTA"
            }
        ));
        jScrollPane1.setViewportView(jtblVentReal);

        pnlOpcVenReal.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de búsqueda"));

        btnBuscVenReal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        btnBuscVenReal.setText("Buscar");

        btnImpriVenReal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        btnImpriVenReal.setText("Imprimir");

        lblDeVenReal.setText("Desde:");

        lblAVenReal.setText("Hasta:");

        javax.swing.GroupLayout pnlOpcVenRealLayout = new javax.swing.GroupLayout(pnlOpcVenReal);
        pnlOpcVenReal.setLayout(pnlOpcVenRealLayout);
        pnlOpcVenRealLayout.setHorizontalGroup(
            pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenDeVenReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeVenReal))
                .addGap(42, 42, 42)
                .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calenAVenFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAVenReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnBuscVenReal)
                .addGap(68, 68, 68)
                .addComponent(btnImpriVenReal)
                .addGap(42, 42, 42))
        );
        pnlOpcVenRealLayout.setVerticalGroup(
            pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                        .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpcVenRealLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblDeVenReal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcVenRealLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAVenReal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calenDeVenReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calenAVenFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlOpcVenRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscVenReal)
                        .addComponent(btnImpriVenReal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVentaRealLayout = new javax.swing.GroupLayout(pnlVentaReal);
        pnlVentaReal.setLayout(pnlVentaRealLayout);
        pnlVentaRealLayout.setHorizontalGroup(
            pnlVentaRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentaRealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVentaRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlVentaRealLayout.createSequentialGroup()
                        .addComponent(pnlOpcVenReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVentaRealLayout.setVerticalGroup(
            pnlVentaRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentaRealLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpcVenReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVentaReal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlVentaReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasRealizadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasRealizadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscVenReal;
    private javax.swing.JButton btnImpriVenReal;
    private com.toedter.calendar.JDateChooser calenAVenFall;
    private com.toedter.calendar.JDateChooser calenDeVenReal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblVentReal;
    private javax.swing.JLabel lblAVenReal;
    private javax.swing.JLabel lblDeVenReal;
    private javax.swing.JPanel pnlOpcVenReal;
    private javax.swing.JPanel pnlVentaReal;
    // End of variables declaration//GEN-END:variables
}
